apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: iap-echoserver
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: "http://rust-iap.localtest.me/authorize"
    #nginx.ingress.kubernetes.io/auth-signin: "http://rust-iap.localtest.me/token"
spec:
  rules:
    - host: iap-test.localtest.me
      http:
        paths:
          - backend:
              serviceName: iap-echoserver
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: iap-echoserver
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    name: iap-echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: iap-echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: iap-echoserver
  template:
    metadata:
      labels:
        name: iap-echoserver
    spec:
      containers:
        - name: echoserver
          image: k8s.gcr.io/echoserver:1.10
          ports:
          - containerPort: 8080
