apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: rust-iap
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: rust-iap.localtest.me
      http:
        paths:
          - backend:
              serviceName: rust-iap
              servicePort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: rust-iap
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    name: rust-iap
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rust-iap
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rust-iap
  template:
    metadata:
      labels:
        name: rust-iap
    spec:
      containers:
        - name: rust-iap
          image: rust-iap
          ports:
          - containerPort: 3000
